### ISSUE TITLE
help help help!!

### ISSUE THREAD

**Issue by 0704681032** [cemartins/websocket-test#1]
can i only use your SpringConfigurator.java  without MyApplication.java ( do not inittail by the servlet but the spring)

like this ? it seems that it doesnot work😄

@ServerEndpoint(value="/ws/createfile/",configurator=SpringConfigurator.class)

**Comment by cemartins** [comment]
Yes, you can, but you have to create a class that implements the ServletContextListener interface and you have to register your endpoint with it, see the example below:

```
package com.audaxys.af.websocket;

import javax.servlet.ServletContext;
import javax.servlet.ServletContextEvent;
import javax.servlet.ServletContextListener;
import javax.websocket.DeploymentException;
import javax.websocket.server.ServerContainer;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

import com.audaxys.af.integration.bll.support.WebsocketMessagingGatewayEndpoint;
import com.audaxys.fw.integration.SunsetWebsocketEndpointConfig;

public class AFWebsocketRegistration implements ServletContextListener {

    private final static Log LOG = LogFactory.getLog(AFWebsocketRegistration.class);

    private final static String SERVER_CONTAINER_ATTRIBUTE = "javax.websocket.server.ServerContainer";

    @Override
    public void contextInitialized(ServletContextEvent sce) {
        ServletContext container = sce.getServletContext();

        final ServerContainer serverContainer = (ServerContainer) container.getAttribute(SERVER_CONTAINER_ATTRIBUTE);
        try {
            serverContainer.addEndpoint(new SunsetWebsocketEndpointConfig(WebsocketMessagingGatewayEndpoint.class, "/wsmsgs"));
        } catch (DeploymentException e) {
            LOG.error("failed to add endpoint");
        }
    }

    @Override
    public void contextDestroyed(ServletContextEvent sce) {
    }

}
```

**Comment by 0704681032** [comment]
WebSocket connection to 'ws://localhost:9090/ws/createfile' failed: Error during WebSocket handshake: Unexpected response code: 404

the key code is that:

serverContainer.addEndpoint(new MyEndpointConfig(MyEndpoint.class, "/ws/createfile/"));

your MyEndpointConfig.java 

your MyEndpoint.java 

i found that onOpen function didnot execute

**Comment by 0704681032** [comment]
@Override
    public void onOpen(Session session, EndpointConfig config) {

```
    System.out.println("websocket connection opened: " + session.getId());

}
```

did not executed

**Comment by 0704681032** [comment]
------Installed extensions:0

**Comment by 0704681032** [comment]
thank you it has been solved!! 
i am a new bird。。

**Comment by cemartins** [comment]
Nice to know that :)
Cheers
